USE [nckh]
SET IDENTITY_INSERT [dbo].[DICH_VU_CAN_HO] ON 

INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-02-01' AS Date), CAST(N'2024-02-03' AS Date), 1)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-02-01' AS Date), CAST(N'2024-02-03' AS Date), 2)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-02-01' AS Date), CAST(N'2024-02-03' AS Date), 4)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-02-01' AS Date), CAST(N'2024-02-03' AS Date), 5)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-03-01' AS Date), CAST(N'2024-03-03' AS Date), 6)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-03-01' AS Date), CAST(N'2024-03-03' AS Date), 7)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-03-01' AS Date), CAST(N'2024-03-03' AS Date), 8)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-03-01' AS Date), CAST(N'2024-03-03' AS Date), 9)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-04-01' AS Date), CAST(N'2024-04-03' AS Date), 10)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-04-01' AS Date), CAST(N'2024-04-03' AS Date), 11)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'**       ', N'CH1       ', 1, CAST(N'2024-04-01' AS Date), CAST(N'2024-04-03' AS Date), 12)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-04-01' AS Date), CAST(N'2024-04-03' AS Date), 13)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-04-01' AS Date), CAST(N'2024-04-03' AS Date), 14)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-05-01' AS Date), CAST(N'2024-05-03' AS Date), 15)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-05-01' AS Date), CAST(N'2024-05-03' AS Date), 16)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-05-01' AS Date), CAST(N'2024-05-03' AS Date), 17)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-05-01' AS Date), CAST(N'2024-05-03' AS Date), 18)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-06-01' AS Date), CAST(N'2024-06-03' AS Date), 19)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-06-01' AS Date), CAST(N'2024-06-03' AS Date), 20)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-06-01' AS Date), CAST(N'2024-06-03' AS Date), 21)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-06-01' AS Date), CAST(N'2024-06-03' AS Date), 22)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-07-01' AS Date), CAST(N'2024-07-03' AS Date), 23)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-07-01' AS Date), CAST(N'2024-07-03' AS Date), 24)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-07-01' AS Date), CAST(N'2024-07-03' AS Date), 25)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-07-01' AS Date), CAST(N'2024-07-03' AS Date), 26)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-08-01' AS Date), CAST(N'2024-08-03' AS Date), 27)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-08-01' AS Date), CAST(N'2024-08-03' AS Date), 28)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-08-01' AS Date), CAST(N'2024-08-03' AS Date), 29)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-08-01' AS Date), CAST(N'2024-08-03' AS Date), 30)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH1       ', 1, CAST(N'2024-05-01' AS Date), NULL, 31)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH1       ', 1, CAST(N'2024-05-01' AS Date), NULL, 32)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV1       ', N'CH2       ', 1, CAST(N'2024-05-01' AS Date), NULL, 33)
INSERT [dbo].[DICH_VU_CAN_HO] ([ma_dich_vu], [ma_can_ho], [so_luong], [ngay_bat_dau], [ngay_ket_thuc], [id]) VALUES (N'DV2       ', N'CH2       ', 1, CAST(N'2024-05-01' AS Date), NULL, 34)
