USE ManageDepartment
GO
DROP TABLE IF EXISTS PHONG_BAN
GO
CREATE TABLE PHONG_BAN(
	Ma_phong_ban NVARCHAR(10) PRIMARY KEY NOT NULL,
	Ten_phong_ban NVARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS THANH_TOAN
GO
CREATE TABLE THANH_TOAN (
	Ma_thanh_toan NVARCHAR(10) NOT NULL PRIMARY KEY,
	So_tai_khoan INT NOT NULL,
	Ten_ngan_hang NVARCHAR(50) NOT NULL
);
GO
DROP TABLE IF EXISTS NHAN_VIEN
GO
CREATE TABLE NHAN_VIEN(
	Ma_nhan_vien NVARCHAR(10) PRIMARY KEY NOT NULL,
	Ho_ten NVARCHAR(50) NOT NULL,
	SDT INT NOT NULL,
	Ma_phong_ban NVARCHAR(10) FOREIGN KEY REFERENCES PHONG_BAN(Ma_phong_ban) NOT NULL,
	Phai NVARCHAR(3) DEFAULT ('NAM'),
	Ngay_sinh DATE NOT NULL,
	CHECK (PHAI = 'NAM' OR PHAI = 'NU'),
);

GO
DROP TABLE IF EXISTS CHU_SO_HUU
GO
CREATE TABLE CHU_SO_HUU(
	Ma_chu_so_huu NVARCHAR(10) PRIMARY KEY NOT NULL,
	Ho_ten NVARCHAR(50) NOT NULL,
	SDT INT NOT NULL,
	Phai NVARCHAR(3) DEFAULT ('NAM'),
	Ngay_sinh DATE NOT NULL,
	CHECK (PHAI = 'NAM' OR PHAI = 'NU'),
);

GO
DROP TABLE IF EXISTS CAN_HO
GO
CREATE TABLE CAN_HO(
	Ma_can_ho NVARCHAR(10) PRIMARY KEY NOT NULL,
	So_nha INT NOT NULL,
	Ma_chu_so_huu NVARCHAR(10) FOREIGN KEY REFERENCES CHU_SO_HUU(Ma_chu_so_huu),
	Dia_chi NVARCHAR(50) NOT NULL
);
GO
DROP TABLE IF EXISTS HOA_DON
GO
CREATE TABLE HOA_DON(
	Ma_hoa_don NVARCHAR(10) PRIMARY KEY NOT NULL,
	Ngay_lap DATE NOT NULL,
	Ma_thanh_toan NVARCHAR(10) NOT NULL FOREIGN KEY REFERENCES THANH_TOAN(Ma_thanh_toan)
);
GO
DROP TABLE IF EXISTS DICH_VU
GO
CREATE TABLE DICH_VU(
	Ma_dich_vu NVARCHAR(10) PRIMARY KEY NOT NULL,
	Ten_dich_vu NVARCHAR(50) NOT NULL,
	
);
GO
DROP TABLE IF EXISTS CHI_TIET_DICH_VU
GO
CREATE TABLE CHI_TIET_DICH_VU(
	Ngay_bat_dau DATE NOT NULL,
	Ngay_ket_thuc DATE NOT NULL,
	Ma_dich_vu NVARCHAR(10) NOT NULL,
	Ma_can_ho NVARCHAR(10) NOT NULL,
	So_luong INT,
	Don_gia INT,
	VAT INT,
	CONSTRAINT PK_CTDV PRIMARY KEY (Ma_dich_vu,Ma_can_ho),
	FOREIGN KEY (Ma_dich_vu) REFERENCES DICH_VU(Ma_dich_vu),
	FOREIGN KEY (Ma_can_ho) REFERENCES CAN_HO(Ma_can_ho)
);
GO
DROP TABLE IF EXISTS CHI_TIET_HOA_DON
GO
CREATE TABLE CHI_TIET_HOA_DON (
	Ma_dich_vu NVARCHAR(10) NOT NULL,
	Ma_hoa_don NVARCHAR(10) NOT NULL,
	Ma_nhan_vien NVARCHAR(10) NOT NULL,
	Ma_can_ho NVARCHAR(10) NOT NULL,
	Ngay_lap DATE NOT NULL,
	Ngay_het_han DATE NOT NULL,
	Tong_tien INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (Ma_dich_vu,Ma_hoa_don,Ma_nhan_vien, Ma_can_ho),
	FOREIGN KEY (Ma_dich_vu,Ma_can_ho) REFERENCES CHI_TIET_DICH_VU(Ma_dich_vu,Ma_can_ho),
	FOREIGN KEY (Ma_hoa_don) REFERENCES HOA_DON(Ma_hoa_don),
	FOREIGN KEY (Ma_nhan_vien) REFERENCES NHAN_VIEN(Ma_nhan_vien),
);