USE BlogManagement
GO
CREATE TABLE AUTHORITY(
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR(255)
);
GO
CREATE TABLE ROLE (
	ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(10)
);
GO
CREATE TABLE ACCOUNT (
	ID INT PRIMARY KEY IDENTITY,
	FIRSTNAME NVARCHAR(100),
	LASTNAME NVARCHAR(100),
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(100),
	GENDER BIT,
	AGE INT,
	BIRTHDATE DATE,
	PHOTO VARCHAR(50),
	TOKEN VARCHAR(50),
	ROLE INT,
	CONSTRAINT FK_ROLE FOREIGN KEY (ROLE) REFERENCES ROLE(ID)
)
GO
CREATE TABLE POST (
	ID INT PRIMARY KEY IDENTITY,
	AUTHOR_ID INT,
	TITLE NVARCHAR(255),
	BODY TEXT,
	CREATE_AT DATETIME,
	UPDATE_AT DATETIME,
	CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES ACCOUNT(ID)
);
GO
CREATE TABLE EMOJI (
	ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(100)
);
GO
CREATE TABLE ACCOUNT_AUTHORITY (
	ID_ACCOUNT INT,
	ID_AUTHORITY INT,
	CONSTRAINT PK_ACCOUNT_AUTHORITY PRIMARY KEY (ID_ACCOUNT, ID_AUTHORITY),
	CONSTRAINT FK_AUTHORITY_ACCOUNT FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID),
	CONSTRAINT FK_ACCOUT_AUTHORITY FOREIGN KEY (ID_AUTHORITY) REFERENCES AUTHORITY(ID)
);
GO
CREATE TABLE CATEGORY (
	ID INT PRIMARY KEY IDENTITY,
	CATEGORY_NAME VARCHAR(100)
);
GO
CREATE TABLE TAG (
	ID INT PRIMARY KEY IDENTITY,
	TAG_NAME VARCHAR(100)
);
GO 
CREATE TABLE COMMENT (
	ID_ACCOUNT INT,
	ID_POST INT,
	BODY NVARCHAR(500),
	CONSTRAINT PK_COMMENT PRIMARY KEY (ID_ACCOUNT, ID_POST),
	CONSTRAINT FK_COMMENT_ACCOUNT FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID),
	CONSTRAINT FK_COMMENT_POST FOREIGN KEY (ID_POST) REFERENCES POST(ID)
);
GO
CREATE TABLE INTERACT (
	ID_ACCOUNT INT,
	ID_POST INT,
	ID_EMOJI INT,
	CONSTRAINT PK_INTERACT PRIMARY KEY (ID_ACCOUNT, ID_POST, ID_EMOJI),
	CONSTRAINT FK_INTERACT_POST FOREIGN KEY (ID_POST) REFERENCES POST(ID),
	CONSTRAINT FK_INTERACT_ACCOUNT FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID),
	CONSTRAINT FK_INTERACT_EMOJI FOREIGN KEY (ID_EMOJI) REFERENCES EMOJI(ID),
);
GO
CREATE TABLE POST_CATEGORY (
	ID_POST INT,
	ID_CATEGORY INT,
	CONSTRAINT PK_POST_CATEGORY PRIMARY KEY (ID_CATEGORY, ID_POST),
	CONSTRAINT FK_CATEGORY_POST FOREIGN KEY (ID_POST) REFERENCES POST(ID),
	CONSTRAINT FK_POST_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID),
);